//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorDeTarefasWeb
{


         public partial class AdicionarTarefa
         {

                  /// <summary>
                  /// txtTitulo control.
                  /// </summary>
                  /// <remarks>
                  /// Auto-generated field.
                  /// To modify move field declaration from designer file to code-behind file.
                  /// </remarks>
                  protected global::System.Web.UI.WebControls.TextBox txtTitulo;

                  /// <summary>
                  /// txtDescricao control.
                  /// </summary>
                  /// <remarks>
                  /// Auto-generated field.
                  /// To modify move field declaration from designer file to code-behind file.
                  /// </remarks>
                  protected global::System.Web.UI.WebControls.TextBox txtDescricao;

                  /// <summary>
                  /// txtStatus control.
                  /// </summary>
                  /// <remarks>
                  /// Auto-generated field.
                  /// To modify move field declaration from designer file to code-behind file.
                  /// </remarks>
                  protected global::System.Web.UI.WebControls.TextBox txtStatus;

                  /// <summary>
                  /// txtPrioridade control.
                  /// </summary>
                  /// <remarks>
                  /// Auto-generated field.
                  /// To modify move field declaration from designer file to code-behind file.
                  /// </remarks>
                  protected global::System.Web.UI.WebControls.TextBox txtPrioridade;

                  /// <summary>
                  /// btnAdicionar control.
                  /// </summary>
                  /// <remarks>
                  /// Auto-generated field.
                  /// To modify move field declaration from designer file to code-behind file.
                  /// </remarks>
                  protected global::System.Web.UI.WebControls.Button btnAdicionar;
         }
}
